<a href="https://colab.research.google.com/github/lara-ms/Aula-C11B/blob/main/Cap5_Exerc%C3%ADcios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios Pandas

---

## EXERCÍCIOS (PARTE 1)

### **Questão 1**

Crie duas Series com os seguintes valores:
- seriesAno1: {‘Java’: 16.25, ‘C’: 16.04, ‘Python’:9.85}

- seriesAno2: {‘C’: 16.21, ‘Python’: 12.12, ‘Java’: 11.68}

In [75]:
import pandas as pd

seriesAno1 = pd.Series({'Java': 16.25, 'C': 16.04, 'Python':9.85})

seriesAno2 = pd.Series({'C': 16.21, 'Python': 12.12, 'Java': 11.68})

print("SerieAno1 :")
print(seriesAno1)

print("\nSerieAno2 :")
print(seriesAno2)

SerieAno1 :
Java      16.25
C         16.04
Python     9.85
dtype: float64

SerieAno2 :
C         16.21
Python    12.12
Java      11.68
dtype: float64

### **Questão 2**

Os valores das Series criadas na **Questão 1** representam as fatias de mercado (porcentagem) de 3 linguagens de programação populares em dois anos consecutivos. Para cada ano, apresente a porcentagem total que elas juntas representam no mercado;

In [76]:
print(f"Porcentagem para o ano 1: {seriesAno1.sum()} %")

print(f"Porcentagem para o ano 2: {seriesAno2.sum()} %")

Porcentagem para o ano 1: 42.14 %
Porcentagem para o ano 2: 40.01 %

### **Questão 3**

Apresente o crescimento/declínio no mercado de cada linguagem do primeiro ano para o segundo ano;

In [77]:
print("Declínio(-)/Crescimento(+) de cada linguagem :")

# subtrai ano 1 do ano 2 para que se fosse declinio ficasse - (mais intuitivo)
diferenca = seriesAno2.sub(seriesAno1, fill_value=0)

print(diferenca)

Declínio(-)/Crescimento(+) de cada linguagem :
C         0.17
Java     -4.57
Python    2.27
dtype: float64

### **Questão 4**

Baseado nos resultados da **Questão 3**, mostre apenas os dados das linguagens que tiveram crescimento;

In [78]:
print("Linguagens que tiveram crescimento : ")

print(diferenca[diferenca > 0])

Linguagens que tiveram crescimento :
C         0.17
Python    2.27
dtype: float64

### **Questão 5**

Se estas porcentagens de crescimento/declínio se mantivessem iguais para os próximos 2 anos, qual seria a linguagem mais popular? Dica: use o método nlargest (1) no final para retornar rapidamente a label e maior valor de uma Series.

In [79]:
# somando ao ultimo ano a diferenca vezes 2 (proximos 2 anos)
proximosAnos = seriesAno2.add(diferenca*2, fill_value=0)

print("Linguagem mais popular :")
print(proximosAnos.nlargest(1))

Linguagem mais popular :
Python    16.66
dtype: float64



---

## EXERCÍCIOS (PARTE 2)

### **Questão 6**

Utilizando do DataFrame exemplo do tópico 5.3 deste material, calcule a média dos elementos da coluna X que são menores que 30;

In [80]:
import numpy as np

# plantando uma semente aleatória
np.random.seed(10)

# criando um dataframe
df = pd.DataFrame(
index=['A', 'B', 'C', 'D', 'E'],
columns=['W', 'X', 'Y', 'Z'],
data=np.random.randint(1, 50, [5, 4]))
print(df)

    W   X   Y   Z
A  10  37  16   1
B  29  26  30  49
C  30   9  10   1
D  43  41  37  17
E  37  48  12  25

In [81]:
print("Media dos elementos em X menores que 30 :")
print(df[df['X'] < 30]['X'].mean())

Media dos elementos em X menores que 30 :
17.5

### **Questão 7**

Utilizando do mesmo DataFrame, apresente a média dos elementos da
linha D usando a função loc() como base e a soma dos elementos da linha E usando a função iloc() como base;

In [82]:
# usando o loc na linha D
print("Media dos elementos da linha D :")
print(df.loc['D'].mean())

# usando o iloc na linha E
print("\nSoma dos elementos da linha E :")
print(df.iloc[4].sum())

Media dos elementos da linha D :
34.5

Soma dos elementos da linha E :
122

### **Questão 8**

Faça um Slicing na matriz mostrando apenas as linhas A, C e E
juntamente com as colunas X e Y. Em seguida, mostre qual seria a soma dos elementos de cada uma destas linhas e cada uma destas colunas.

In [83]:
slicing = df.loc[['A', 'C', 'E'], ['X', 'Y']]
print("Slicing da Matriz :")
print(slicing)

print('\n')
for i in range(len(slicing)):
  print(f"Soma dos elementos da {i}ª linha  : {slicing.iloc[i].sum()}")

print('\n')
for i in range(len(slicing.columns)):
  print(f"Soma dos elementos da {i}ª coluna : {slicing.iloc[:,i].sum()}")

Slicing da Matriz :
    X   Y
A  37  16
C   9  10
E  48  12


Soma dos elementos da 0ª linha  : 53
Soma dos elementos da 1ª linha  : 19
Soma dos elementos da 2ª linha  : 60


Soma dos elementos da 0ª coluna : 94
Soma dos elementos da 1ª coluna : 38

##

---

## EXERCÍCIOS (PARTE 3)

### **Questão 1**

Carregue o Dataset paises.csv e em seguida mostre:
- Quais são os países da OCEANIA;
- Quantos países são da OCEANIA;

**Dica:** para busca de padrões textuais no Pandas, use métodos da subclasse str da
Series. Ex: series.str.contains(‘texto’)

In [84]:
import pandas as pd

# lendo o arquivo csv
df_Paises = pd.read_csv('paises.csv', delimiter=';')

# para mostrar de forma organizadinha
display(df_Paises)

# mostrando as colunas
print(df_Paises.columns)

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700,36.0,3.2,12.13,0.22,87.65,1.0,46.60,20.34,0.380,0.240,0.380
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500,86.5,71.2,21.09,4.42,74.49,3.0,15.11,5.22,0.232,0.188,0.579
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000,70.0,78.1,3.22,0.25,96.53,1.0,17.14,4.61,0.101,0.600,0.298
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000,97.0,259.5,10.00,15.00,75.00,2.0,22.46,3.27,0.000,0.000,0.000
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000,100.0,497.2,2.22,0.00,97.78,3.0,8.71,6.25,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,West Bank,NEAR EAST,2460492,5860,419.9,0.00,2.98,19.62,800,0.0,145.2,16.90,18.97,64.13,3.0,31.67,3.92,0.090,0.280,0.630
223,Western Sahara,NORTHERN AFRICA,273008,266000,1.0,0.42,0.00,0.00,0,0.0,0.0,0.02,0.00,99.98,1.0,0.00,0.00,0.000,0.000,0.400
224,Yemen,NEAR EAST,21456188,527970,40.6,0.36,0.00,61.50,800,50.2,37.2,2.78,0.24,96.98,1.0,42.89,8.30,0.135,0.472,0.393
225,Zambia,SUB-SAHARAN AFRICA,11502010,752614,15.3,0.00,0.00,88.29,800,80.6,8.2,7.08,0.03,92.90,2.0,41.00,19.93,0.220,0.290,0.489
226,Zimbabwe,SUB-SAHARAN AFRICA,12236805,390580,31.3,0.00,0.00,67.69,1900,90.7,26.8,8.32,0.34,91.34,2.0,28.01,21.84,0.179,0.243,0.579

Index(['Country', 'Region', 'Population', 'Area (sq. mi.)',
       'Pop. Density (per sq. mi.)', 'Coastline (coast/area ratio)',
       'Net migration', 'Infant mortality (per 1000 births)',
       'GDP ($ per capita)', 'Literacy (%)', 'Phones (per 1000)', 'Arable (%)',
       'Crops (%)', 'Other (%)', 'Climate', 'Birthrate', 'Deathrate',
       'Agriculture', 'Industry', 'Service'],
      dtype='object')

In [85]:
# primeiro limita na coluna Region e depois procura a str Oceania
paises_oceania = df_Paises[df_Paises['Region'].str.contains('OCEANIA')]

print(" -> Paises da OCEANIA :")
# aqui mostro so os nomes dos paises e sem que aparece aquele indice na frente
print(paises_oceania['Country'].to_string(index=False))

print(f"\n -> Quantidade de Paises da OCEANIA : {len(paises_oceania)}")

 -> Paises da OCEANIA :
      American Samoa
           Australia
        Cook Islands
                Fiji
    French Polynesia
                Guam
            Kiribati
    Marshall Islands
Micronesia, Fed. St.
               Nauru
       New Caledonia
         New Zealand
  N. Mariana Islands
               Palau
    Papua New Guinea
               Samoa
     Solomon Islands
               Tonga
              Tuvalu
             Vanuatu
   Wallis and Futuna

 -> Quantidade de Paises da OCEANIA : 21

### **Questão 2**

Encontre o nome e a região do país que possui a maior população segundo este Dataset;

In [86]:
# procurando o maior na coluna Population
maior_pop = df_Paises.nlargest(1, 'Population')

print(" -> Maior Populaçao :")
# mostrando de forma organizadinha
display(maior_pop[['Country', 'Region']])

 -> Maior Populaçao :

   Country                         Region
42  China   ASIA (EX. NEAR EAST)

### **Questão 3**

Agrupe os países por Regiões. Em seguida, mostre a média de alfabetização (Literacy (%)) de cada região do planeta;

In [87]:
# agrupando por regiao
group_region = df_Paises.groupby('Region')

# mostrando a media de Literacy (%)
group_region = df_Paises.groupby('Region')
display(group_region['Literacy (%)'].mean())

Region
ASIA (EX. NEAR EAST)                   79.553571
BALTICS                                99.733333
C.W. OF IND. STATES                    98.725000
EASTERN EUROPE                         72.816667
LATIN AMER. & CARIB                    88.640000
NEAR EAST                              69.581250
NORTHERN AFRICA                        56.033333
NORTHERN AMERICA                       78.200000
OCEANIA                                71.914286
SUB-SAHARAN AFRICA                     61.284314
WESTERN EUROPE                         80.821429
Name: Literacy (%), dtype: float64

### **Questão 4**

Busque o nome de todos os países do Dataset que não possuem costa marítima (Coastline (coast/area ratio) == 0) e guarde-os em um novo arquivo chamado noCoast.csv;

In [88]:
# buscando os paises que nao possuem costa maritma apenas os nomes
paises_semCosta = df_Paises[df_Paises['Coastline (coast/area ratio)'] == 0]['Country']

# salvando em um novo arquivo com separacao por , (para conseguir ver pelo colab)
paises_semCosta.to_csv('noCoast.csv', sep=',', index=False)

### **Questão 5**

Faça uma função que receba a taxa de mortalidade de cada país (Deathrate) e retorne o texto ‘Balanced’ caso o valor seja < 9 e ‘Urgent’ caso contrário. Em seguida, crie um campo no Dataset chamado ‘Humanitarian Help’ que receba estes valores para cada país. No final, mostre o Dataset para verificar se a inserção da nova coluna foi feita com sucesso.

In [89]:
# funcao que retorna Balanced ou Urgent com base na mortalidade
def help_mortalidade(x):
  if x < 9:
    return 'Balanced'
  else:
    return 'Urgent'

df_Paises['Humanitarian Help'] = df_Paises['Deathrate'].apply(help_mortalidade)

display(df_Paises)

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),...,Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service,Humanitarian Help
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700,36.0,...,12.13,0.22,87.65,1.0,46.60,20.34,0.380,0.240,0.380,Urgent
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500,86.5,...,21.09,4.42,74.49,3.0,15.11,5.22,0.232,0.188,0.579,Balanced
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000,70.0,...,3.22,0.25,96.53,1.0,17.14,4.61,0.101,0.600,0.298,Balanced
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000,97.0,...,10.00,15.00,75.00,2.0,22.46,3.27,0.000,0.000,0.000,Balanced
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000,100.0,...,2.22,0.00,97.78,3.0,8.71,6.25,0.000,0.000,0.000,Balanced
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,West Bank,NEAR EAST,2460492,5860,419.9,0.00,2.98,19.62,800,0.0,...,16.90,18.97,64.13,3.0,31.67,3.92,0.090,0.280,0.630,Balanced
223,Western Sahara,NORTHERN AFRICA,273008,266000,1.0,0.42,0.00,0.00,0,0.0,...,0.02,0.00,99.98,1.0,0.00,0.00,0.000,0.000,0.400,Balanced
224,Yemen,NEAR EAST,21456188,527970,40.6,0.36,0.00,61.50,800,50.2,...,2.78,0.24,96.98,1.0,42.89,8.30,0.135,0.472,0.393,Balanced
225,Zambia,SUB-SAHARAN AFRICA,11502010,752614,15.3,0.00,0.00,88.29,800,80.6,...,7.08,0.03,92.90,2.0,41.00,19.93,0.220,0.290,0.489,Urgent
226,Zimbabwe,SUB-SAHARAN AFRICA,12236805,390580,31.3,0.00,0.00,67.69,1900,90.7,...,8.32,0.34,91.34,2.0,28.01,21.84,0.179,0.243,0.579,Urgent

## EXERCÍCIOS (PARTE 4)

### **Questão 6**

Agrupe os países por região e mostre as estatísticas descritivas da coluna Population de cada região. Em seguida, mostre apenas as 5 primeiras linhas
deste resultado;

In [90]:
# agrupando por região
group_region = df_Paises.groupby('Region')

# mostrando as estatisticas descritivas da coluna Population
print(' -> Estatisticas Descritivas :')
group_regionPop = group_region['Population'].describe()
display(group_regionPop)

# mostrando as 5 primeiras linhas
print('\n -> 5 primeiras linhas :')
display(group_regionPop.head(5))

 -> Estatisticas Descritivas :

,count,mean,std,min,25%,50%,75%,max
Region,,,,,,,,
ASIA (EX. NEAR EAST),28.0,1.317137e+08,3.102610e+08,359008.0,5899398.25,26336502.5,85669393.75,1.313974e+09
BALTICS,3.0,2.394991e+06,1.135572e+06,1324333.0,1799534.00,2274735.0,2930320.50,3.585906e+06
C.W. OF IND. STATES,12.0,2.334013e+07,3.973450e+07,2976372.0,4947558.25,7641217.0,18251716.50,1.428935e+08
EASTERN EUROPE,12.0,9.992893e+06,1.054246e+07,2010347.0,4266475.50,6412407.5,10044864.25,3.853687e+07
LATIN AMER. & CARIB,45.0,1.248499e+07,3.235397e+07,9439.0,117848.00,1065842.0,8989046.00,1.880782e+08
NEAR EAST,16.0,1.219177e+07,1.819645e+07,698585.0,2170984.00,3488139.5,19525067.75,7.041396e+07
NORTHERN AFRICA,6.0,2.690119e+07,2.901349e+07,273008.0,6969319.00,21552552.5,33163467.00,7.888701e+07
NORTHERN AMERICA,5.0,6.633446e+07,1.305404e+08,7026.0,56361.00,65773.0,33098932.00,2.984442e+08
OCEANIA,21.0,1.577698e+06,4.519602e+06,11810.0,57794.00,114689.0,274578.00,2.026408e+07
SUB-SAHARAN AFRICA,51.0,1.469484e+07,2.309189e+07,7502.0,1540931.00,8090068.0,15621837.00,1.318597e+08
WESTERN EUROPE,28.0,1.415500e+07,2.315879e+07,27928.0,74381.00,4921096.0,10626417.00,8.242230e+07

 -> 5 primeiras linhas :

,count,mean,std,min,25%,50%,75%,max
Region,,,,,,,,
ASIA (EX. NEAR EAST),28.0,1.317137e+08,3.102610e+08,359008.0,5899398.25,26336502.5,85669393.75,1.313974e+09
BALTICS,3.0,2.394991e+06,1.135572e+06,1324333.0,1799534.00,2274735.0,2930320.50,3.585906e+06
C.W. OF IND. STATES,12.0,2.334013e+07,3.973450e+07,2976372.0,4947558.25,7641217.0,18251716.50,1.428935e+08
EASTERN EUROPE,12.0,9.992893e+06,1.054246e+07,2010347.0,4266475.50,6412407.5,10044864.25,3.853687e+07
LATIN AMER. & CARIB,45.0,1.248499e+07,3.235397e+07,9439.0,117848.00,1065842.0,8989046.00,1.880782e+08

### Questão 7

Crie uma função customizada que receba a coluna Infant mortality (per 1000 births) de um país e retorne o valor reduzido em 15% (simulando assim uma meta de redução da mortalidade infantil). Aplique esta função à coluna usando o
método apply() e, em seguida, concatene a coluna original com a coluna resultante lado a lado para se fazer uma comparação;

In [91]:
# metodo que retorna o valor reduzido 15% (100% - 15%)
def reduzir_15(x):
 return x*0.85

# pegando a coluna Infant mortality
infant_mort1 = df_Paises['Infant mortality (per 1000 births)']

# aplicando o metodo
infant_mort2 = df_Paises['Infant mortality (per 1000 births)'].apply(reduzir_15)

# concatenando e mostrando as duas series
pd.concat([infant_mort1, infant_mort2], axis=1)

     Infant mortality (per 1000 births)  Infant mortality (per 1000 births)
0                                163.07                            138.6095
1                                 21.52                             18.2920
2                                 31.00                             26.3500
3                                  9.27                              7.8795
4                                  4.05                              3.4425
..                                  ...                                 ...
222                               19.62                             16.6770
223                                0.00                              0.0000
224                               61.50                             52.2750
225                               88.29                             75.0465
226                               67.69                             57.5365

[227 rows x 2 columns]

### **Questão 8**

Remova a coluna Coastline
(coast/area Ratio) do dataset. Em seguida, salve este novo dataset em um arquivo chamado paises_sem_coastline.csv.

In [92]:
# removendo a coluna Coastline do dataset
df_Paises = df_Paises.drop('Coastline (coast/area ratio)', axis=1)

# salvando em um arquivo
df_Paises.to_csv('paises_sem_coastline.csv', sep=',', index=False)